
driver_names = {
    0: "SAI",
    1: "KVY",
    2: "RIC",
    6: "RAI",
    7: "HAM",
    9: "VER",
    10: "HUL",
    11: "MAG",
    12: "GRO",
    13: "VET",
    14: "PER",
    15: "BOT",
    17: "OCO",
    19: "STR",
    20: "BAR",
    21: "GIL",
    22: "MUR",
    23: "ROT",
    24: "COR",
    25: "LEV",
    26: "Jonas Schiffer",
    27: "Alain Forest",
    28: "Jay Letourneau",
    29: "Esto Saari",
    30: "Yasar Atiyeh",
    31: "Callisto Calabresi",
    32: "Naota Izum",
    33: "Howard Clarke",
    34: "Wilhelm Kaufmann",
    35: "Marie Laursen",
    36: "Flavio Nieves",
    37: "Peter Belousov",
    38: "Klimek Michalski",
    39: "Santiago Moreno",
    40: "Benjamin Coppens",
    41: "Noah Visser",
    42: "Gert Waldmuller",
    43: "Julian Quesada",
    44: "Daniel Jones",
    45: "Artem Markelov",
    46: "Tadasuke Makino",
    47: "Sean Gelael",
    48: "Nyck De Vries",
    49: "Jack Aitken",
    50: "RUS",
    51: "Maximilian Günther",
    52: "Nirei Fukuzumi",
    53: "Luca Ghiotto",
    54: "NOR",
    55: "Sérgio Sette Câmara",
    56: "Louis Delétraz",
    57: "Antonio Fuoco",
    58: "LEC",
    59: "GAS",
    62: "ALB",
    63: "LAT",
    64: "Dorian Boccolacci",
    65: "Niko Kari",
    66: "Roberto Merhi",
    67: "Arjun Maini",
    68: "Alessio Lorandi",
    69: "Ruben Meijer",
    70: "Rashid Nair",
    71: "Jack Tremblay",
    74: "GIO",
    75: "Robert Kubica",
    78: "Nobuharu Matsushita",
    79: "Nikita Mazepin",
    80: "Guanyu Zhou",
    81: "Mick Schumacher",
    82: "Callum Ilott",
    83: "Juan Manuel Correa",
    84: "Jordan King",
    85: "Mahaveer Raghunathan",
    86: "Tatiana Calderón",
    87: "Anthoine Hubert",
    88: "Giuliano Alesi",
    89: "Ralph Boschung"}